name: Lint and Test Charts

on: pull_request

jobs:
  lint-test:
    runs-on: buildjet-8vcpu-ubuntu-2204
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: "50"

      - name: Set up Helm
        uses: azure/setup-helm@v3
        with:
          version: v3.10.2

      # Python is required because `ct lint` runs Yamale (https://github.com/23andMe/Yamale) and
      # yamllint (https://github.com/adrienverge/yamllint) which require Python
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.11.1

      - name: Set up chart-testing
        uses: helm/chart-testing-action@v2.5.0
        with:
          version: v3.8.0

      - name: Run chart-testing (lint)
        run: ct lint --charts ./ --config=ct.yml
                
      - name: Create kind cluster
        uses: helm/kind-action@v1.4.0

